[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "crypto-agility"
version = "0.0.1"
description = "Hybrid KEM/AES-GCM stubs for QST"
authors = [{name="QST"}]
requires-python = ">=3.10"
